#include "printfhead.h"

int main(void)
{
	//точность не уитывает знак
	//ширина учитывает знак!
	//printf("origg - hello world!\n");
	//int a = ft_printf("%07d|\n", -53);
	//printf("%5.d|\n", 0);
	//printf("%5.0d|\n", 0);
	//printf("%05d|\n", 0);
	//printf("%05d|\n", 0);
	//ft_printf("%5.d|\n", 0);
	//ft_printf("%5.0d|\n", 0);
	//ft_printf("%05d|\n", 0);
	//ft_printf("%05d|\n", 0);
	//printf("---\n");
	// printf("%12p|\n", s);
	// printf("%p|\n", s);
	// ft_printf("%p|\n", s);
	// printf("%p|\n", &number);
	// ft_printf("%p|\n", &number);
	// printf("%.15p|\n", &number);
	// ft_printf("%.15p|\n", &number);
	// printf("%18.15p|\n", &number);
	// ft_printf("%18.15p|\n", &number);
	// 	printf("%p|\n", NULL);
	// ft_printf("%p|\n", NULL);
	// printf("%18.17p|\n", NULL);
	// ft_printf("%18.17p|\n", NULL);
	// printf("%.5p|\n", NULL);
	// ft_printf("%.5p|\n", NULL);
	// printf("%.p|\n", 0);
	// ft_printf("%.p|\n", 0);
	// %0*.*d, %0*.*d, %0*.*d, %0*.*d, %0*.*d, %0*.*d, %0*.*d
	// printf("%0*.*d|\n", 2, -2, 0);
	// ft_printf("%0*.*d|\n", 2, -2, 0);
	// printf("%0*.*d|\n", 2, -2, 2);
	// ft_printf("%0*.*d|\n", 2, -2, 2);
	//8, - 12, 123456789,     , -12345678,   97, -2147483648, 2147483647
	// printf("%0*.0d|\n", 5, -12);
	// 	ft_printf("%0*.0d|\n", 5, -12);
	// printf("%0*.d|\n", 5, -12);
	// 	ft_printf("%0*.d|\n", 5, -12);
	// printf("%0*.*d|\n", 5,0, -12);
	// 	ft_printf("%0*.*d|\n", 5,0, -12);
	// printf("%0*d|\n",-4, 8);
	// 	ft_printf("%0*d|\n",-4, 8);
	// printf("%0*.*d|\n", 5, -2,  -12);
	// 	ft_printf("%0*.*d|\n", 5, -2,  -12);
	// printf("%0*.*d|\n", 5, 0,  -12);
	// 	ft_printf("%0*.*d|\n", 5, 0,  -12);
	// printf("%0*d|\n", 5, -12);
	// 	ft_printf("%0*d|\n", 5, -12);
	// printf("%4d|\n", -12);
	// 	ft_printf("%4d|\n", -12);
	// printf("%4d|\n", -12);
	// 	ft_printf("%4d|\n", -12);
	// printf("%0*.*d|\n", 4, 0, -12);
	// 	ft_printf("%0*.*d|\n", 4, 0, -12);
	// printf("%0*.*d|\n", -10, 0, -12);
	// 	ft_printf("%0*.*d|\n", -10, 0, -12);
	// printf("%*.*d|\n", -10, 0, -12);
	// 	ft_printf("%*.*d|\n", -10, 0, -12);
	// printf("%0*.*d|\n", 4, -2, -12);
	// 	ft_printf("%0*.*d|\n", 4, -2, -12);
	// printf("%010d|\n", 5);
	// 	ft_printf("%010d|\n", 5);
	// printf("%*p|\n", 8, NULL);
	// ft_printf("%*p|\n", 8, NULL);
	// printf("%.*p|\n", 5, 0);
	// ft_printf("%.*p|\n", 5, 0);
	printf("%.p|\n", 0);
	ft_printf("%.p|\n", 0);
	printf("%.*p|\n", -3, 0);
	ft_printf("%.*p|\n", -3, 0);
	printf("\n");
	printf("%*p|\n", 8, NULL);
	ft_printf("%*p|\n", 8, NULL);
	printf("\n");
	printf("%-*p|\n", 8, NULL);
	ft_printf("%-*p|\n", 8, NULL);
	printf("\n");
	printf("%*p|\n",4, NULL);
	ft_printf("%*p|\n",4, NULL);
	printf("\n");
	printf("%2p|\n", NULL);
	ft_printf("%2p|\n", NULL);
	printf("\n");
	printf("%-5.2p|\n", NULL);
	ft_printf("%-5.2p|\n", NULL);


	// printf("%10p|\n", NULL);
	// printf("%5.*p|\n", -8, NULL);
	// printf("%*.p|\n", 8, NULL);
	// printf("%.5p|\n", NULL);
	// printf("%10.5p|\n", NULL);
	// printf("%.*p|\n", -6, NULL);
	// printf("%-*p|\n", 8, NULL);
	// printf("%*p|\n", 8, NULL);
	// printf("%0*p|\n", 8, NULL);
	// printf("%0.2p|\n", NULL);
	// printf("%010p|\n", NULL);

	//ft_printf("%07d|\n", -54);
	//printf("%-7d|\n", 0);
	//ft_printf("%-7d|\n", 0);
	//ft_printf("%-07d|\n", 53);
	//int b = printf(NULL);
	//printf("%d = %d\n", a,b);
	//ft_printf("hello, %.s|\n", "gavin");
	//printf("hello, %.s|\n", "gavin");
	//ft_printf("hello, %.0s|\n", "gavin");
	//printf("hello, %.0s|\n", "gavin");
	//ft_printf("%32s|\n", "abc");
	//printf("%32s|\n", "abc");
	//printf("%-05%");
	//ft_printf("%-05%");
	//printf("%.-*d|\n", 5, 123);
	//printf("---%d---\n", ++i);
	//	ft_printf("%07.10d\n", number);
	//	printf("%07.10d\n", number);
	//printf("---%d---\n", ++i);
	//	ft_printf("%30X|\n", number);
	//	printf("%30X|\n", number);
	//printf("---%d---\n", ++i);
	//	ft_printf("%10.10x|\n", number);
	//	printf("%10.10x|\n", number);
	//printf("---%d---\n", ++i);
	//	ft_printf("%-10.1x|\n", number);
	//	printf("%-10.1x|\n", number);
	//printf("---%d---\n", ++i);
	//	ft_printf("%030.1i|\n", number);
	//	printf("%030.1i|\n", number);
	//printf("---%d---\n", ++i);
	//	ft_printf("%30.1s|\n", s);
	//	printf("%30.1s|\n", s);
	//printf("---%d---\n", ++i);
	//	ft_printf("%11.10s|\n", s);
	//	printf("%11.10s|\n", s);
	//printf("---%d---\n", ++i);
	//	ft_printf("%10.3s|\n", s);
	//	printf("%10.3s|\n", s);
	//printf("---%d---\n", ++i);
	//	ft_printf("%10.3s|\n", NULL);
	//	printf("%10.3s|\n", NULL);
	//printf("---%d---\n", ++i);
	//	ft_printf("%10.3s---%10.1s|\n", s,s);
	//	printf("%10.3s---%10.1s|\n", s,s);
	//printf("---%d---\n", ++i);
	//	ft_printf("%s|\n", s);
	//	printf("%s|\n", s);
	//printf("---%d---\n", ++i);
	//	ft_printf("%-30s|\n", s);
	//	printf("%-30s|\n", s);
	//printf("---%d---\n", ++i);
	//	int b = ft_printf("%030.1s|\n", s);
	//	int c = printf("%030.1s|\n", s);
	//printf(" %d = %d\n", b, c);
	//printf("---%d---\n", ++i);
	//	ft_printf("%30.100c|\n", 'a');
	//	printf("%30.100c|\n", 'a');
	//printf("---%d---\n", ++i);
	//	int j = ft_printf("%s", "testing testing\n");
	//	int k = printf("%s", "testing testing\n");
	//printf("%d = %d\n", j, k);
	//printf("---%d---\n", ++i);
	//	 j = ft_printf("hello, world!\n");
	//	 k = printf("hello, world!\n");
	//printf("%d = %d\n", j, k);
	//printf("---%d---\n", ++i);
	//	 j = ft_printf("");
	//	 k = printf("");
	//printf("%d = %d\n", j, k);
	//printf("---%d---\n", ++i);
	//printf("%*.*d\n", j, k, 123);
	//ft_printf("%*.*d\n", j, k, 123);
	//ft_printf("this %s is %s", "", "string\n");
	//int a = ft_printf("hello werled!\n");
	//int b = ft_printf("hello werled!\n");
	//printf("%d = %d", a, b);

	//asterisk problem
	return 0;
}
